# Generated by Django 5.2.7 on 2025-10-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField(default='["", "", "", "", "", "", "", "", ""]')),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O'), ('D', 'Draw')], max_length=1, null=True)),
                ('vs_bot', models.BooleanField(default=False)),
                ('player_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_o_games', to='tictactoe.player')),
                ('player_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_x_games', to='tictactoe.player')),
            ],
        ),
    ]
